shadow = false
borders = "simple"

[colors]
    background = "black"
    shadow     = "black"
    view       = "black"

    primary   = "white"
    secondary = "white"
    tertiary  = "white"

    title_primary   = "blue"
    title_secondary = "blue"

    highlight          = "white"
    highlight_inactive = "#777777"
